name: Check codestyle

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  check-codestyle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: xdebug
          
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 15.14.0

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}
      
      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: npm-${{ hashFiles('package-lock.json') }}

      - name: Run composer install
        run: composer install -n --prefer-dist
        
      - name: Run npm install
        run: npm install

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Check PHP codestyle
        run: |
          vendor/bin/php-cs-fixer fix -v --dry-run --stop-on-violation --using-cache=no
          
      - name: Check JS/TS codestyle
        run: |
          npx prettier --check "resources/js/**"
